---
- name: Config Setup of App Options
  zip: "55436"
  country: 'US'
  state: 'MN'
  stocks: 
    - 'PLNT'
    - 'GOOGL'
    - 'MMM'
    - 'KR'
    - 'F' 
    - 'TWTR'
    - 'RKT'
    - 'FSLY' 
    - 'CCO'
    - '^IXIC'
    - '^DJI'
    - '^GSPC'

