---
- name: Config Setup of App Options
  zip: "55343"
  country: 'US'
  state: 'MN'
  stocks:
    - 'GOOGL'
    - 'MMM'
    - 'KR'
    - 'F'
    - 'NIO'
    - 'NKO'
    - 'ABT'
    - 'PLNT'
    - 'TWTR'
    - '^IXIC'
    - '^DJI'
    - '^GSPC'

