---
- name: Config Setup of App Options
  zip: "80211"
  country: 'US'
  state: 'CO'
  stocks: 
    - 'KR'
    - 'F' 
    - 'TWTR'
    - 'RKT'
    - 'FSLY' 
    - 'CCO'
    - '^IXIC'
    - '^DJI'
    - '^GSPC'

