---
- name: Config Setup of App Options
  zip: "55343"
  country: 'US'
  state: 'MN'
  stocks:
    - 'GOOGL'
    - 'MMM'
    - 'KR'
    - 'F'
    - 'NIO'
    - 'NKO'
    - 'ABT'
    - 'SOS'
    - 'GGB'
    - 'NTRP'
    - 'TMUS'
    - 'ABBV'
    - 'PLNT'
    - 'TWTR'
    - 'GC=F'
    - 'SL=F'
    - 'HG=F'
    - '^NQTWT10'
    - '^NQTWTWD'
    - '^NQTW'
    - '^NQKR'
    - '^NQKR10'
    - '^KQ11'
    - '^NQASIAN'
    - '^NQASIA10'
    - '^NQASIAT'
    - '^VIX'
    - '^IXIC'
    - '^DJI'
    - '^GSPC'

